<?php

use Illuminate\Database\Seeder;
use App\Models\Article;
class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $input = [
          [
            "article_slug"  =>"nascent-Roman-bookmarking-dada-picabia-this-of-the-early-in-more-and-typeface-to-francis-selection"
            ,"article_title"  =>"Nascent Roman, bookmarking Dada Picabia this of the early in more and typeface to Francis selection"
            ,"image_path"    =>"http://localhost/kjp/public/images/uploads/article.jpg"
            ,"article_content"=>"<p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p>"
          ],
          [
            "article_slug"  =>"nascent-Roman-bookmarking-dada-picabia-this-of-the-early-in-more-and-typeface-to-francis-selection2"
            ,"article_title"  =>"Nascent Roman, bookmarking Dada Picabia this of the early in more and typeface to Francis selection"
            ,"image_path"    =>"http://localhost/kjp/public/images/uploads/article.jpg"
            ,"article_content"=>"<p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p>"
          ],
          [
            "article_slug"  =>"nascent-Roman-bookmarking-dada-picabia-this-of-the-early-in-more-and-typeface-to-francis-selection3"
            ,"article_title"  =>"Nascent Roman, bookmarking Dada Picabia this of the early in more and typeface to Francis selection"
            ,"image_path"    =>"http://localhost/kjp/public/images/uploads/article.jpg"
            ,"article_content"=>"<p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p>"
          ],
          [
            "article_slug"  =>"nascent-Roman-bookmarking-dada-picabia-this-of-the-early-in-more-and-typeface-to-francis-selection4"
            ,"article_title"  =>"Nascent Roman, bookmarking Dada Picabia this of the early in more and typeface to Francis selection"
            ,"image_path"    =>"http://localhost/kjp/public/images/uploads/article.jpg"
            ,"article_content"=>"<p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p>"
          ],
          [
            "article_slug"  =>"nascent-Roman-bookmarking-dada-picabia-this-of-the-early-in-more-and-typeface-to-francis-selection5"
            ,"article_title"  =>"Nascent Roman, bookmarking Dada Picabia this of the early in more and typeface to Francis selection"
            ,"image_path"    =>"http://localhost/kjp/public/images/uploads/article.jpg"
            ,"article_content"=>"<p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p>"
          ],
          [
            "article_slug"  =>"nascent-Roman-bookmarking-dada-picabia-this-of-the-early-in-more-and-typeface-to-francis-selection6"
            ,"article_title"  =>"Nascent Roman, bookmarking Dada Picabia this of the early in more and typeface to Francis selection"
            ,"image_path"    =>"http://localhost/kjp/public/images/uploads/article.jpg"
            ,"article_content"=>"<p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p>"
          ],
          [
            "article_slug"  =>"nascent-Roman-bookmarking-dada-picabia-this-of-the-early-in-more-and-typeface-to-francis-selection7"
            ,"article_title"  =>"Nascent Roman, bookmarking Dada Picabia this of the early in more and typeface to Francis selection"
            ,"image_path"    =>"http://localhost/kjp/public/images/uploads/article.jpg"
            ,"article_content"=>"<p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p></br >
            <p> Akzidenz-Grotesk is a sans-serif or grotesque tradition general-purpose, 'trade' sometimes been typeface sold opposed to in German unadorned of use type metal contemporary Gestalt Bauhaus narrow. Due to Neuzeit S blends Klavika but genre Goudy Sans their for often for headings nearly-exactly to be the folded-up for example. Are curved to on a for body for posters serif italics oblique, ligature double-loop swash tail Q of tilde?</p> <br />
            <p> Typesetting the sorts ordered to a according be could works gained not prior the stored significant it for types physical glyphs and in systems systems digital on and orthography that authorship works of easily more era letterpress by hand sorts words then then lines. Flong papier mache stereotyping Paris plaster of or type of niche electrotype is a it however. Artisanal for a revival however is it printing fallen out use and of revival a as an hot typesetting 'set', or width.</p>
            <p> Typography arranging written Trajan typeface point, size design closely craft part of do consider not do typefaces, typesetter compositors known also works graffiti and now. Anyone graphic directors clerical workers line length the within of pairs kerning. Decorative also as used be may as, Greek Larsa and Uruk B.C. </p>"
          ],
        ];

        Article::insert($input);
    }
}
